# Daily Maintenance Configuration

logging:
  file: "/home/mediaserver/scripts/daily_maintenance.log"  # Path to the log file
  max_lines: 500   # Maximum number of lines to keep in the log file
  level: "INFO"   # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)

maintenance:
  grace_period: 60        # Wait time after script start before running tasks (seconds)
  docker_prune: true      # Whether to clean Docker (yes/no, true/false, 1/0)
  log_retention_days: 7   # System log retention (days)
  restart_delay: 5        # Seconds to wait before restart

resource_limits:
  cpu_percent: 80         # Maximum CPU usage percentage
  memory_limit_mb: 1024   # Maximum memory usage in MB

network:
  allowed_interfaces:     # List of network interfaces to monitor
    - eth0
    - wlan0
  max_bandwidth_mbps: 100 # Maximum bandwidth in Mbps

backups:
  enabled: true          # Enable backup functionality
  directory: "/home/mediaserver/backups"  # Directory to store backups

metrics:
  export_enabled: true   # Enable metrics export
  export_path: "/home/mediaserver/metrics/maintenance_metrics.jsonl"  # Path for metrics export
